server:
  port: 8083


spring:
  jpa:
    hibernate:
      ddl-auto: create
      database-platform: postgresql
  datasource:
  url: "jdbc:postgresql://localhost:5432/library"
  username: postgres
  password: '[!T@ni@_1979]'